-- -----------------------------------------------------
-- Schema ecommerce_olist
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS ecommerce_olist DEFAULT CHARACTER SET utf8 ;
USE ecommerce_olist ;

-- -----------------------------------------------------
-- Table ecommerce_olist.OLIST_GEOLOCATION_DATASET
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS OLIST_GEOLOCATION_DATASET (
  GEOLOCATION_ZIP_CODE_PREFIX INT NOT NULL,
  GEOLOCATION_LAT FLOAT NULL,
  GEOLOCATION_LNG FLOAT NULL,
  GEOLOCATION_CITY TEXT NULL,
  GEOLOCATION_STATE TEXT NULL,
  PRIMARY KEY (GEOLOCATION_ZIP_CODE_PREFIX))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ecommerce_olist.PRODUCT_CATEGORY_NAME_TRANSLATION
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS PRODUCT_CATEGORY_NAME_TRANSLATION (
  PRODUCT_CATEGORY_ID INT NOT NULL,
  PRODUCT_CATEGORY_NAME TEXT NOT NULL,
  PRODUCT_CATEGORY_NAME_ENGLISH TEXT NULL,
  PRIMARY KEY (PRODUCT_CATEGORY_ID))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table ecommerce_olist.OLIST_PRODUCTS_DATASET
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS OLIST_PRODUCTS_DATASET (
  PRODUCT_ID INT NOT NULL,
  PRODUCT_CATEGORY_ID INT NULL,
  PRODUCT_NAME_LENGHT INT NULL,
  PRODUCT_DESCRIPTION_LENGHT DECIMAL NULL,
  PRODUCT_PHOTOS_QTY INT NULL,
  PRODUCT_WEIGHT_G INT NULL,
  PRODUCT_LENGTH_CM INT NULL,
  PRODUCT_HEIGHT_CM INT NULL,
  PRODUCT_WIDTH_CM INT NULL,
  PRODUCT_CATEGORY_NAME TEXT NOT NULL,
  PRIMARY KEY (PRODUCT_ID),
  INDEX fk_OLIST_PRODUCTS_DATASET_PRODUCT_CATEGORY_NAME_TRANSLATION_idx (PRODUCT_CATEGORY_ID ASC) VISIBLE,
  CONSTRAINT fk_OLIST_PRODUCTS_DATASET_PRODUCT_CATEGORY_NAME_TRANSLATION1
    FOREIGN KEY (PRODUCT_CATEGORY_ID)
    REFERENCES PRODUCT_CATEGORY_NAME_TRANSLATION (PRODUCT_CATEGORY_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ecommerce_olist.OLIST_CUSTOMERS_DATASET
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS OLIST_CUSTOMERS_DATASET (
  CUSTOMER_ID INT NOT NULL,
  CUSTOMER_UNIQUE_ID TEXT NULL,
  CUSTOMER_CITY TEXT NULL,
  CUSTOMER_STATE TEXT NULL,
  CUSTOMER_ZIP_CODE_PREFIX INT NOT NULL,
  PRIMARY KEY (CUSTOMER_ID),
  INDEX fk_OLIST_CUSTOMERS_DATASET_OLIST_GEOLOCATION_DATASET_idx (CUSTOMER_ZIP_CODE_PREFIX ASC) VISIBLE,
  CONSTRAINT fk_OLIST_CUSTOMERS_DATASET_OLIST_GEOLOCATION_DATASET
    FOREIGN KEY (CUSTOMER_ZIP_CODE_PREFIX)
    REFERENCES OLIST_GEOLOCATION_DATASET (GEOLOCATION_ZIP_CODE_PREFIX)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ecommerce_olist.OLIST_ORDERS_DATASET
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS OLIST_ORDERS_DATASET (
  ORDER_ID INT NOT NULL,
  ORDER_STATUS TEXT NULL,
  ORDER_PURCHASE_TIMESTAMP DATE NULL,
  ORDER_APPROVED_AT DATE NULL,
  ORDER_DELIVERED_CARRIER_DATE DATE NULL,
  ORDER_DELIVERED_CUSTOMER_DATE DATE NULL,
  ORDER_ESTIMATED_DELIVERY_DATE DATE NULL,
  CUSTOMER_ID INT NOT NULL,
  PRIMARY KEY (ORDER_ID),
  INDEX fk_OLIST_ORDERS_DATASET_OLIST_CUSTOMERS_DATASET1_idx (CUSTOMER_ID ASC) VISIBLE,
  CONSTRAINT fk_OLIST_ORDERS_DATASET_OLIST_CUSTOMERS_DATASET1
    FOREIGN KEY (CUSTOMER_ID)
    REFERENCES OLIST_CUSTOMERS_DATASET (CUSTOMER_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table ecommerce_olist.OLIST_ORDER_REVIEWS_DATASET
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS OLIST_ORDER_REVIEWS_DATASET (
  REVIEW_ID INT NOT NULL,
  REVIEW_SCORE TEXT NULL,
  REVIEW_COMMENT_TITLE TEXT NULL,
  REVIEW_COMMENT_MESSAGE TEXT NULL,
  REVIEW_CREATION_DATE TEXT NULL,
  REVIEW_ANSWER_TIMESTAMP TEXT NULL,
  ORDER_ID INT NOT NULL,
  PRIMARY KEY (REVIEW_ID),
  INDEX fk_OLIST_ORDER_REVIEWS_DATASET_OLIST_ORDERS_DATASET1_idx (ORDER_ID ASC) VISIBLE,
  CONSTRAINT fk_OLIST_ORDER_REVIEWS_DATASET_OLIST_ORDERS_DATASET1
    FOREIGN KEY (ORDER_ID)
    REFERENCES OLIST_ORDERS_DATASET (ORDER_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ecommerce_olist.OLIST_SELLERS_DATASET
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS OLIST_SELLERS_DATASET (
  SELLER_ID INT NOT NULL,
  SELLER_CITY TEXT NULL,
  SELLER_STATE TEXT NULL,
  SELLER_ZIP_CODE_PREFIX INT NOT NULL,
  PRIMARY KEY (SELLER_ID, SELLER_ZIP_CODE_PREFIX),
  INDEX fk_OLIST_SELLERS_DATASET_OLIST_GEOLOCATION_DATASET1_idx (SELLER_ZIP_CODE_PREFIX ASC) VISIBLE,
  CONSTRAINT fk_OLIST_SELLERS_DATASET_OLIST_GEOLOCATION_DATASET1
    FOREIGN KEY (SELLER_ZIP_CODE_PREFIX)
    REFERENCES OLIST_GEOLOCATION_DATASET (GEOLOCATION_ZIP_CODE_PREFIX)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ecommerce_olist.OLIST_ORDER_ITEMS_DATASET
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS OLIST_ORDER_ITEMS_DATASET (
  ORDER_ITEM_ID INT NOT NULL,
  SHIPPING_LIMIT_DATE DATE NULL,
  PRICE FLOAT NULL,
  FREIGHT_VALUE FLOAT NULL,
  ORDER_ID INT NOT NULL,
  PRODUCT_ID INT NOT NULL,
  SELLER_ID INT NOT NULL,
  PRIMARY KEY (ORDER_ITEM_ID),
  INDEX fk_OLIST_ORDER_ITEMS_DATASET_OLIST_ORDERS_DATASET1_idx (ORDER_ID ASC) VISIBLE,
  INDEX fk_OLIST_ORDER_ITEMS_DATASET_OLIST_PRODUCTS_DATASET1_idx (PRODUCT_ID ASC) VISIBLE,
  INDEX fk_OLIST_ORDER_ITEMS_DATASET_OLIST_SELLERS_DATASET1_idx (SELLER_ID ASC) VISIBLE,
  CONSTRAINT fk_OLIST_ORDER_ITEMS_DATASET_OLIST_ORDERS_DATASET1
    FOREIGN KEY (ORDER_ID)
    REFERENCES OLIST_ORDERS_DATASET (ORDER_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_OLIST_ORDER_ITEMS_DATASET_OLIST_PRODUCTS_DATASET1
    FOREIGN KEY (PRODUCT_ID)
    REFERENCES OLIST_PRODUCTS_DATASET (PRODUCT_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_OLIST_ORDER_ITEMS_DATASET_OLIST_SELLERS_DATASET1
    FOREIGN KEY (SELLER_ID)
    REFERENCES OLIST_SELLERS_DATASET (SELLER_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ecommerce_olist.OLIST_ORDER_PAYMENTS_DATASET
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS OLIST_ORDER_PAYMENTS_DATASET (
  PAYMENT_SEQUENTIAL INT NULL,
  PAYMENT_TYPE TEXT NULL,
  PAYMENT_INSTALLMENTS INT NULL,
  PAYMENT_VALUE FLOAT NULL,
  ORDER_ID INT NOT NULL,
  PRIMARY KEY (ORDER_ID),
  INDEX fk_OLIST_ORDER_PAYMENTS_DATASET_OLIST_ORDERS_DATASET1_idx (ORDER_ID ASC) VISIBLE,
  CONSTRAINT fk_OLIST_ORDER_PAYMENTS_DATASET_OLIST_ORDERS_DATASET1
    FOREIGN KEY (ORDER_ID)
    REFERENCES OLIST_ORDERS_DATASET (ORDER_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- SET SQL_MODE=@OLD_SQL_MODE;
-- SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
-- SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
